### ISSUE TITLE
Configure continuous integration

### ISSUE THREAD

**Issue by jml** [LeastAuthority/haskell-magic-wormhole#2]
I've already set up CircleCI for running integration tests. However, since moving the repository to LeastAuthority, I'm not able to set it up.

If someone with repo-admin permission could go to https://circleci.com/add-projects/gh/LeastAuthority and add haskell-magic-wormhole, that would be great.

Alternatively, could someone give me repo-admin permission and I'll do that.

*Or*, if CircleCI is inappropriate, let me know and I'll try to set up efficient CI using LeastAuthority's preferred tech.

**Comment by exarkun** [comment]
I think I did that?  CircleCI UI has changed since I last looked at it though.

**Comment by jml** [comment]
All good, thanks!
